---
apiVersion: v1
kind: Service
metadata:
  name: counter-service
  namespace: task-05
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: counter
  ports:
  - port: 8080
    targetPort: 8080
    name: http
