#!/usr/bin/env python3
"""
JWT Token Decoder for Instructors
Decodes and displays evaluation tokens generated by the assessment system
"""

import sys
import json
import jwt
import os
from datetime import datetime

def decode_token(token, secret, verify=True):
    """
    Decode a JWT token and display its contents

    Args:
        token: The JWT token string
        secret: The secret key used to sign the token
        verify: Whether to verify the signature (default: True)
    """
    try:
        if verify:
            # Decode and verify signature
            payload = jwt.decode(token, secret, algorithms=['HS256'])
            print("✅ Token signature verified successfully")
        else:
            # Decode without verification (just to read contents)
            payload = jwt.decode(token, options={"verify_signature": False}, algorithms=['HS256'])
            print("⚠️  Token decoded WITHOUT signature verification")

        print("\n" + "="*70)
        print("JWT TOKEN CONTENTS")
        print("="*70)

        # Display basic info
        print(f"\nStudent ID:    {payload.get('student_id')}")
        print(f"Task ID:       {payload.get('task_id')}")
        print(f"Score:         {payload.get('score')}/{payload.get('max_score')}")
        print(f"Timestamp:     {payload.get('timestamp')}")
        print(f"Status:        {payload.get('status')}")

        # Display results summary
        results = payload.get('results', {})
        if results:
            print(f"\n{'Evaluation Criteria':<45} {'Result':>10}")
            print("-"*70)

            passed = sum(1 for v in results.values() if v is True)
            total = len(results)

            for criterion, result in sorted(results.items()):
                status = "✓ PASS" if result else "✗ FAIL"
                print(f"{criterion:<45} {status:>10}")

            print("-"*70)
            print(f"{'Total':45} {passed}/{total}")

        # Display full payload as JSON
        print("\n" + "="*70)
        print("FULL PAYLOAD (JSON)")
        print("="*70)
        print(json.dumps(payload, indent=2))

        return payload

    except jwt.ExpiredSignatureError:
        print("❌ Error: Token has expired")
        return None
    except jwt.InvalidTokenError as e:
        print(f"❌ Error: Invalid token - {e}")
        print("\nTrying to decode without verification...")
        return decode_token(token, secret, verify=False)
    except Exception as e:
        print(f"❌ Error decoding token: {e}")
        return None


def main():
    """Main entry point"""

    print("="*70)
    print("JWT TOKEN DECODER - Kubernetes Assessment Framework")
    print("="*70)
    print()

    # Get secret key
    secret = os.environ.get('JWT_SECRET') or os.environ.get('API_KEY')

    if not secret:
        print("⚠️  Warning: JWT_SECRET and API_KEY not found in environment")
        secret = input("Enter JWT secret key: ").strip()
        if not secret:
            print("❌ Error: Secret key is required")
            sys.exit(1)
    else:
        print(f"✅ Using secret from environment variable")

    # Get token
    if len(sys.argv) > 1:
        token = sys.argv[1]
    else:
        print("\nEnter JWT token (or path to file containing token):")
        token_input = input("> ").strip()

        # Check if it's a file path
        if os.path.isfile(token_input):
            with open(token_input, 'r') as f:
                content = f.read().strip()
                # Try to parse as JSON first
                try:
                    data = json.loads(content)
                    token = data.get('eval_token', content)
                except:
                    token = content
        else:
            token = token_input

    if not token:
        print("❌ Error: Token is required")
        sys.exit(1)

    print(f"\nToken length: {len(token)} characters")
    print(f"Token preview: {token[:50]}...")
    print()

    # Decode token
    payload = decode_token(token, secret)

    if payload:
        print("\n✅ Token decoded successfully!")
    else:
        print("\n❌ Failed to decode token")
        sys.exit(1)


if __name__ == '__main__':
    main()
