---
apiVersion: v1
kind: Service
metadata:
  name: config-demo-service
  namespace: task-04
spec:
  type: ClusterIP
  selector:
    app: config-demo
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
