# INSTRUCTOR REFERENCE SOLUTION
# This file should not be accessible to students

apiVersion: v1
kind: Namespace
metadata:
  name: task-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: task-01
  labels:
    app: nginx-web
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi