apiVersion: v1
kind: Service
metadata:
  name: key-value-headless
  namespace: task-02
spec:
  clusterIP: None
  selector:
    app: key-value
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: key-value-svc
  namespace: task-02
spec:
  serviceName: "key-value-headless"
  replicas: 4
  selector:
    matchLabels:
      app: key-value
  template:
    metadata:
      labels:
        app: key-value
    spec:
      containers:
      - name: app
        image: kvstore:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Mi
